# ONBUILD instructions in base-image/Dockerfile are used to
# perform certain actions based on the presence of specific
# files (such as conda-linux-64.lock, start) in this repo.
# Refer to the base-image/Dockerfile for documentation.
FROM quay.io/igabriel185/maap_pangeo_ubi_base:latest

LABEL authors="gabriel"



CMD ["tail", "-f", "/dev/null"]